locals {
  service_delegation_actions = {
    "GitHub.Network/networkSettings"         = ["virtualNetworks/subnets/join/action"]
    "Microsoft.ApiManagement/service"        = ["virtualNetworks/subnets/join/action", "virtualNetworks/subnets/prepareNetworkPolicies/action"]
    "Microsoft.Apollo/npu"                   = ["networkinterfaces/*", "virtualNetworks/subnets/join/action"]
    "Microsoft.App/environments"             = ["virtualNetworks/subnets/join/action"]
    "Microsoft.App/testClients"              = ["virtualNetworks/subnets/join/action"]
    "Microsoft.AVS/PrivateClouds"            = ["networkinterfaces/*"]
    "Microsoft.AzureCosmosDB/clusters"       = ["virtualNetworks/subnets/join/action"]
    "Microsoft.BareMetal/AzureHostedService" = ["networkinterfaces/*", "virtualNetworks/subnets/join/action"]
    # "Microsoft.BareMetal/AzureHPC"                    = [] # Need Microsoft.Network/AllowInternalDelegations
    # "Microsoft.BareMetal/AzurePaymentHSM"             = [] # Need Microsoft.Network/AllowInternalDelegations
    "Microsoft.BareMetal/AzureVMware" = ["networkinterfaces/*", "virtualNetworks/subnets/join/action"]
    "Microsoft.BareMetal/CrayServers" = ["networkinterfaces/*", "virtualNetworks/subnets/join/action"]
    # "Microsoft.BareMetal/MonitoringServers"           = [] # Need Microsoft.Network/AllowInternalDelegations
    "Microsoft.Batch/batchAccounts"               = ["virtualNetworks/subnets/action"]
    "Microsoft.CloudTest/hostedpools"             = ["virtualNetworks/subnets/join/action"]
    "Microsoft.CloudTest/images"                  = ["virtualNetworks/subnets/join/action"]
    "Microsoft.CloudTest/pools"                   = ["virtualNetworks/subnets/join/action"]
    "Microsoft.Codespaces/plans"                  = ["virtualNetworks/subnets/join/action"]
    "Microsoft.ContainerInstance/containerGroups" = ["virtualNetworks/subnets/action"]
    "Microsoft.ContainerService/managedClusters"  = ["virtualNetworks/subnets/join/action"]
    # "Microsoft.ContainerService/TestClients"          = [] # Need Microsoft.Network/AllowInternalDelegations
    "Microsoft.Databricks/workspaces"                 = formatlist("virtualNetworks/subnets/%s", ["join/action", "prepareNetworkPolicies/action", "unprepareNetworkPolicies/action"])
    "Microsoft.DBforMySQL/flexibleServers"            = ["virtualNetworks/subnets/join/action"]
    "Microsoft.DBforMySQL/servers"                    = ["virtualNetworks/subnets/join/action"]
    "Microsoft.DBforMySQL/serversv2"                  = ["virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/flexibleServers"       = ["virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/serversv2"             = ["virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/singleServers"         = ["virtualNetworks/subnets/join/action"]
    "Microsoft.DelegatedNetwork/controller"           = ["virtualNetworks/subnets/join/action"]
    "Microsoft.DevCenter/networkConnection"           = ["virtualNetworks/subnets/join/action"]
    "Microsoft.DocumentDB/cassandraClusters"          = ["virtualNetworks/subnets/join/action"]
    "Microsoft.Fidalgo/networkSettings"               = ["virtualNetworks/subnets/join/action"]
    "Microsoft.HardwareSecurityModules/dedicatedHSMs" = ["networkinterfaces/*", "virtualNetworks/subnets/join/action"]
    "Microsoft.Kusto/clusters"                        = formatlist("virtualNetworks/subnets/%s", ["join/action", "prepareNetworkPolicies/action", "unprepareNetworkPolicies/action"])
    "Microsoft.LabServices/labplans"                  = ["virtualNetworks/subnets/join/action"]
    "Microsoft.Logic/integrationServiceEnvironments"  = ["virtualNetworks/subnets/action"]
    "Microsoft.MachineLearningServices/workspaces"    = ["virtualNetworks/subnets/join/action"]
    "Microsoft.Netapp/volumes"                        = ["networkinterfaces/*", "virtualNetworks/subnets/join/action"]
    "Microsoft.Network/dnsResolvers"                  = ["virtualNetworks/subnets/join/action"]
    # "Microsoft.Network/managedResolvers"              = [] # Not supported by Azure
    # "Microsoft.Network/fpgaNetworkInterfaces"         = [] # Need Microsoft.Network/AllowInternalDelegations
    # "Microsoft.Network/networkWatchers"               = [] # Not supported by Azure
    # "Microsoft.Network/virtualNetworkGateways"        = [] # InternalServerError
    "Microsoft.Orbital/orbitalGateways"              = ["publicIPAddresses/join/action", "virtualNetworks/subnets/join/action", "virtualNetworks/read", "publicIPAddresses/read"]
    "Microsoft.PowerPlatform/enterprisePolicies"     = ["virtualNetworks/subnets/join/action"]
    "Microsoft.PowerPlatform/vnetaccesslinks"        = ["virtualNetworks/subnets/join/action"]
    "Microsoft.ServiceFabricMesh/networks"           = ["virtualNetworks/subnets/action"]
    "Microsoft.ServiceNetworking/trafficControllers" = ["virtualNetworks/subnets/join/action"]
    "Microsoft.Singularity/accounts/networks"        = ["networkinterfaces/*", "virtualNetworks/subnets/join/action"]
    "Microsoft.Singularity/accounts/npu"             = ["networkinterfaces/*", "virtualNetworks/subnets/join/action"]
    "Microsoft.Sql/managedInstances"                 = formatlist("virtualNetworks/subnets/%s", ["join/action", "prepareNetworkPolicies/action", "unprepareNetworkPolicies/action"])
    # "Microsoft.Sql/managedInstancesOnebox"            = [] # Need Microsoft.Network/AllowInternalDelegations
    # "Microsoft.Sql/managedInstancesStage"             = [] # Need Microsoft.Network/AllowInternalDelegations
    # "Microsoft.Sql/managedInstancesTest"              = [] # Need Microsoft.Network/AllowInternalDelegations
    # "Microsoft.Sql/servers"                           = [] # Not supported by Azure
    "Microsoft.StoragePool/diskPools"         = ["virtualNetworks/read"]
    "Microsoft.StreamAnalytics/streamingJobs" = ["virtualNetworks/subnets/join/action"]
    "Microsoft.Synapse/workspaces"            = ["virtualNetworks/subnets/join/action"]
    "Microsoft.Web/hostingEnvironments"       = ["virtualNetworks/subnets/action"]
    "Microsoft.Web/serverFarms"               = ["virtualNetworks/subnets/action"]
    "NGINX.NGINXPLUS/nginxDeployments"        = ["virtualNetworks/subnets/join/action"]
    "PaloAltoNetworks.Cloudngfw/firewalls"    = ["virtualNetworks/subnets/join/action"]
    "Qumulo.Storage/fileSystems"              = ["virtualNetworks/subnets/join/action"]
  }
}
