name: Experimental

on:
  push:
    branches: ['*-beta']
    paths-ignore:
      - 'examples/**'
      - 'LICENSE'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Download environment
        env:
          URL_TESTING: ${{ secrets.URL_TESTING }}
        run: curl -o testing.tf "$URL_TESTING"

      - name: Download
        uses: actions/checkout@v2.3.4
        with:
          path: virtual-network

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: Terraform destroy
        run: terraform destroy -auto-approve
